import type { NextPage } from 'next'
import Head from 'next/head'
import Banner from '../components/banner'
import Footer from '../components/footer'
import Navbar from '../components/navbar'
import Skills from '../components/skills'
import Test from '../components/test'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>highlight scrolling</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <Banner />
        <Skills />
        <Footer />
        <Footer />
      </main>

    </div>
  )
}

export default Home

